### ISSUE TITLE
read server URL from a redirector

### ISSUE THREAD

**Issue by open744** [open744/terramaster#9]
This URL points to a scenery server (nearest geo-IP? is it true?):

http://scenery.flightgear.org/svn-server

Use the result of this query instead of hardcoding the URL.

See https://github.com/FlightGear/simgear/commit/6683092bb216604914b6e0b42733b7ec9876af2c#diff-9efb2948f9e27aa43304a6832efd1ecd

**Comment by wkitty42** [comment]
what's the status on this issue? terramaster has been mentioned in a discussion on the dev mailing list... some folks are wanting to use terramaster to update their scenery because terrasync is too slow while flying... we can't update to the latest scenery until this issue is fixed... i'd do it and put up a pull request but i don't know java any more :disappointed:

**Comment by fojac** [comment]
@open744 yes, it's true, the shown URL should point you to the nearest geoIP terrasync server - or proxy.
I think we all see the corresponding line to update in svn.java, could you update it as I have no right to do so ?
Thanks,
Oliver

**Comment by open744** [comment]
fixed in release 1.2

**Comment by wkitty42** [comment]
@open744 : this is not an issue but please contact me at wkitty42-at-gmail-dotcom as i don't know how to get hold of you otherwise... prefix your post subject with [terramaster-dev] so it passes my filters... thanks!!
